/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sala.gltf -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sala.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" position={[-0.596, 2.016, -2]} rotation={[-Math.PI / 2, 0, 1.385]} scale={0.035}>
        <group name="3872891b59a147cda77ef350e18b9f40fbx" rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="CarUP_LP_UpCar_M1_0" geometry={nodes.CarUP_LP_UpCar_M1_0.geometry} material={materials.UpCar_M1} />
          <group name="FrameBack_LP" position={[0, 1.26, -8.723]} rotation={[0.271, 0, 0]} scale={0.017}>
            <mesh name="FrameBack_LP_Chrome_M_0" geometry={nodes.FrameBack_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, -0.001, 0]} />
          </group>
          <mesh name="Backbump_LP_Chrome_M_0" geometry={nodes.Backbump_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 0.614, -8.555]} rotation={[-0.208, 0, 0]} scale={[1, 0.719, 0.243]} />
          <mesh name="BackChromelamp_LP_Chrome_M_0" geometry={nodes.BackChromelamp_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 1.081, -8.755]} rotation={[0.213, 0, 0]} scale={[0.07, 0.07, 0.041]} />
          <mesh name="Backhandle_LP_Chrome_M_0" geometry={nodes.Backhandle_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0.455, -1.28, -2.939]} rotation={[0, 0, 0.228]} scale={[1, 1.429, 1.071]} />
          <mesh name="BackLock_LP_Chrome_M_0" geometry={nodes.BackLock_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0.46, -0.052, -5.57]} rotation={[0, 1.56, 0]} />
          <mesh name="Backlogo_LP_Chrome_M_0" geometry={nodes.Backlogo_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 1.194, -8.725]} rotation={[0.163, 0, 0]} scale={[1.607, 0.09, 0.058]} />
          <mesh name="BacksideChromewheel_LP_Chrome_M_0" geometry={nodes.BacksideChromewheel_LP_Chrome_M_0.geometry} material={materials.Chrome_M} />
          <mesh name="ChromeBackGlass_LP_Chrome_M_0" geometry={nodes.ChromeBackGlass_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 3.093, -3.177]} rotation={[-0.541, 0, 0]} scale={[0.074, 0.029, 0.074]} />
          <mesh name="FrontBump_LP_Chrome_M_0" geometry={nodes.FrontBump_LP_Chrome_M_0.geometry} material={materials.Chrome_M} />
          <mesh name="frontBumpTooth_LP_Chrome_M_0" geometry={nodes.frontBumpTooth_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[1.2, -0.036, 7.047]} rotation={[0.442, -0.06, 0.028]} scale={[0.067, 0.866, 0.366]} />
          <mesh name="FrontChromeglass_LP_Chrome_M_0" geometry={nodes.FrontChromeglass_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 0.298, -0.584]} rotation={[0.186, 0, 0]} />
          <mesh name="Frontchromemask_LP_Chrome_M_0" geometry={nodes.Frontchromemask_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0, 0.961, 7.52]} rotation={[0.562, 0, 0]} scale={[0.132, 0.027, 0.121]} />
          <mesh name="FrontHandle_LP_Chrome_M_0" geometry={nodes.FrontHandle_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[0.412, -1.431, -0.148]} rotation={[0, 0, 0.228]} scale={[1, 1.429, 1.071]} />
          <mesh name="Frontsidechrome_LP_Chrome_M_0" geometry={nodes.Frontsidechrome_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[4.023, -1.762, 0.058]} rotation={[0, -0.21, 0]} scale={[0.983, 0.959, 0.959]} />
          <mesh name="Lock_LP_Chrome_M_0" geometry={nodes.Lock_LP_Chrome_M_0.geometry} material={materials.Chrome_M} />
          <mesh name="Radio_LP_Chrome_M_0" geometry={nodes.Radio_LP_Chrome_M_0.geometry} material={materials.Chrome_M} />
          <mesh name="Sidechrome1_LP_Chrome_M_0" geometry={nodes.Sidechrome1_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[2.996, 0.325, 3.111]} rotation={[0.034, -0.008, -0.244]} scale={[0.063, 0.161, 0.801]} />
          <mesh name="Sidechrome2_LP_Chrome_M_0" geometry={nodes.Sidechrome2_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[3.009, 0.372, 1.748]} rotation={[0.034, -0.007, -0.217]} scale={[0.063, 0.161, 0.801]} />
          <mesh name="Sidechrome3_LP_Chrome_M_0" geometry={nodes.Sidechrome3_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[3.018, 0.484, -1.365]} rotation={[0.034, -0.007, -0.192]} scale={[0.063, 0.161, 0.801]} />
          <mesh name="Sidechrome4_LP_Chrome_M_0" geometry={nodes.Sidechrome4_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[3.018, 0.564, -3.154]} rotation={[-0.065, -0.007, -0.217]} scale={[0.063, 0.161, 0.074]} />
          <mesh name="Sidechrome5_LP_Chrome_M_0" geometry={nodes.Sidechrome5_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[3.084, 0.647, -6.177]} rotation={[0.035, 0, 0]} scale={[0.063, 0.161, 0.801]} />
          <mesh name="Sidechromedoor_LP_Chrome_M_0" geometry={nodes.Sidechromedoor_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[2.476, 2.205, 0.935]} rotation={[-0.375, -0.105, 0.297]} scale={[0.028, 0.037, 0.03]} />
          <mesh name="SideChromewheel_LP_Chrome_M_0" geometry={nodes.SideChromewheel_LP_Chrome_M_0.geometry} material={materials.Chrome_M} />
          <mesh name="SideWindow_LP_Chrome_M_0" geometry={nodes.SideWindow_LP_Chrome_M_0.geometry} material={materials.Chrome_M} position={[2.243, 2.935, 0.623]} rotation={[0, 0, 0.504]} scale={[0.015, 0.068, 0.068]} />
          <mesh name="BackLapmFrame_LP_FrontChromes_M_0" geometry={nodes.BackLapmFrame_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[1.912, 1.127, -8.393]} scale={[2.055, 0.326, 0.549]} />
          <mesh name="BackLapmPartition_LP_FrontChromes_M_0" geometry={nodes.BackLapmPartition_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} />
          <mesh name="chevroletLogo_LP_FrontChromes_M_0" geometry={nodes.chevroletLogo_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} />
          <mesh name="ColorLamp_LP_FrontChromes_M_0" geometry={nodes.ColorLamp_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} />
          <mesh name="Exhaust_LP_FrontChromes_M_0" geometry={nodes.Exhaust_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[2.326, 0.264, -7.279]} rotation={[1.474, 0, 0]} scale={[0.101, 0.847, 0.101]} />
          <mesh name="FrameLapm_LP_FrontChromes_M_0" geometry={nodes.FrameLapm_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} />
          <mesh name="FrontCoverLamp_LP_FrontChromes_M_0" geometry={nodes.FrontCoverLamp_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[2.064, 0.653, 6.896]} rotation={[0.253, 0.045, -0.012]} scale={[1.087, 0.561, 0.114]} />
          <mesh name="Grill_LP_FrontChromes_M_0" geometry={nodes.Grill_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[0, 0.648, 6.989]} rotation={[0.022, 0.007, -0.002]} scale={[4.176, 0.536, 0.447]} />
          <mesh name="ID_LP_FrontChromes_M_0" geometry={nodes.ID_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[0, -0.171, 7.092]} rotation={[0.412, 0, 0]} scale={[0.797, 0.567, 0.031]} />
          <mesh name="IDBack_LP_FrontChromes_M_0" geometry={nodes.IDBack_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[0, 0.532, -8.501]} rotation={[2.73, 0.004, 3.133]} scale={[0.797, 0.567, 0.031]} />
          <mesh name="LampBulb_LP_FrontChromes_M_0" geometry={nodes.LampBulb_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[0, 0, 2.147]} scale={[1, 1, 0.693]} />
          <mesh name="LampMirror_LP_FrontChromes_M_0" geometry={nodes.LampMirror_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} position={[0, 0, 0.084]} />
          <mesh name="SideLamp_LP_FrontChromes_M_0" geometry={nodes.SideLamp_LP_FrontChromes_M_0.geometry} material={materials.FrontChromes_M} />
          <mesh name="BackGlass_LP_Window_M_0" geometry={nodes.BackGlass_LP_Window_M_0.geometry} material={materials.Window_M} />
          <mesh name="FrontGlass_LP_Window_M_0" geometry={nodes.FrontGlass_LP_Window_M_0.geometry} material={materials.Window_M} />
          <mesh name="GlassLapm_LP_Window_M_0" geometry={nodes.GlassLapm_LP_Window_M_0.geometry} material={materials.Window_M} />
          <mesh name="SideGlass_LP_Window_M_0" geometry={nodes.SideGlass_LP_Window_M_0.geometry} material={materials.Window_M} />
          <group name="armholderdoor_LP" position={[0, 0, -2.477]} scale={[1.004, 0.998, 0.998]}>
            <mesh name="Basearmholder_LP_Indoor_M_0" geometry={nodes.Basearmholder_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 0, 2.482]} scale={[0.996, 1.002, 1.002]} />
            <mesh name="Dooropener_LP_Indoor_M_0" geometry={nodes.Dooropener_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 0, 2.482]} scale={[0.996, 1.002, 1.002]} />
          </group>
          <group name="Cloks_LP" position={[0, 0.101, 0.006]}>
            <mesh name="ArrowClock_LP_Indoor_M_0" geometry={nodes.ArrowClock_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, -0.101, -0.006]} />
            <mesh name="BaseClock_LP_Indoor_M_0" geometry={nodes.BaseClock_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, -0.101, -0.006]} />
          </group>
          <group name="Drive_LP" position={[1.143, 0.098, 4.025]} rotation={[-1.147, -1.388, -0.044]} scale={0.617}>
            <mesh name="BaseDrive_LP_Indoor_M_0" geometry={nodes.BaseDrive_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 4.931, 0]} scale={0.203} />
            <mesh name="BracketDrive_LP_Indoor_M_0" geometry={nodes.BracketDrive_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[-3.372, 5.733, 1.308]} rotation={[1.487, 0.461, -1.367]} scale={1.62} />
            <mesh name="DonutDrive_LP_Indoor_M_0" geometry={nodes.DonutDrive_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 5.409, 0]} scale={[1, 0.144, 1]} />
            <mesh name="Leaver_LP_Indoor_M_0" geometry={nodes.Leaver_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0.105, 4.75, 0.235]} rotation={[1.483, 0.054, -1.932]} scale={0.058} />
          </group>
          <group name="inDoorMirror_LP" position={[0, -1.317, 1.286]} scale={0.775}>
            <mesh name="BviewMirror_LP_Indoor_M_0" geometry={nodes.BviewMirror_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 5.214, 0]} scale={[0.852, 0.194, 0.099]} />
            <mesh name="MirrorHandle_LP_Indoor_M_0" geometry={nodes.MirrorHandle_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 5.456, 0.01]} rotation={[-0.742, 0, 0]} scale={[0.036, 0.274, 0.036]} />
          </group>
          <group name="mirror_LP" position={[-0.62, 2.895, 1.561]} rotation={[0, 0, -0.684]} scale={0.75}>
            <mesh name="Mirror_LP_Indoor_M_0" geometry={nodes.Mirror_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[4.44, 2.091, 0]} rotation={[1.636, 0.029, -0.405]} scale={0.244} />
            <mesh name="MirrorBracket_LP_Indoor_M_0" geometry={nodes.MirrorBracket_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[4.472, 1.783, 0.201]} rotation={[Math.PI / 2, 0.127, 0]} scale={[0.03, 0.143, 0.061]} />
          </group>
          <group name="Wcleaner_LP" position={[0.056, 2.436, -2.281]} rotation={[0.784, 0.023, -0.077]} scale={1.245}>
            <mesh name="Wcleaner_CleanerArm_LP_Indoor_M_0" geometry={nodes.Wcleaner_CleanerArm_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[-0.1, -0.101, 2.676]} rotation={[-0.781, -0.071, 0.038]} scale={0.803} />
            <mesh name="Wcleaner_CleanerBow_LP_Indoor_M_0" geometry={nodes.Wcleaner_CleanerBow_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[-0.1, -0.101, 2.676]} rotation={[-0.781, -0.071, 0.038]} scale={0.803} />
            <mesh name="Wcleaner_CleanerMotor_LP_Indoor_M_0" geometry={nodes.Wcleaner_CleanerMotor_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[-0.1, -0.101, 2.676]} rotation={[-0.781, -0.071, 0.038]} scale={0.803} />
            <mesh name="Wcleaner_CleanerRubber_LP_Indoor_M_0" geometry={nodes.Wcleaner_CleanerRubber_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[-0.1, -0.101, 2.676]} rotation={[-0.781, -0.071, 0.038]} scale={0.803} />
          </group>
          <group name="WindowHandle_LP" position={[-2.874, 1.073, 1.58]} rotation={[0.789, 0, -Math.PI / 2]} scale={0.092}>
            <mesh name="endHandle_LP_Indoor_M_0" geometry={nodes.endHandle_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[20.398, 31.226, -3.825]} rotation={[0, -0.789, Math.PI / 2]} scale={10.866} />
            <mesh name="HandleBase_LP_Indoor_M_0" geometry={nodes.HandleBase_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[20.398, 31.226, -3.825]} rotation={[0, -0.789, Math.PI / 2]} scale={10.866} />
          </group>
          <mesh name="ArmBrake_LP_Indoor_M_0" geometry={nodes.ArmBrake_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[1.191, 0.43, 2.649]} rotation={[0.298, 0, 0]} scale={0.065} />
          <mesh name="PedalBrake_LP_Indoor_M_0" geometry={nodes.PedalBrake_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[1.19, 0.35, 2.523]} rotation={[0.248, 0, 0]} scale={[0.334, 0.176, 0.081]} />
          <mesh name="PedalGas_LP_Indoor_M_0" geometry={nodes.PedalGas_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0.621, 0.396, 2.664]} rotation={[0.298, 0.081, 0.259]} scale={[0.185, 0.463, 0.039]} />
          <mesh name="CouchDown_LP_Indoor_M_0" geometry={nodes.CouchDown_LP_Indoor_M_0.geometry} material={materials.Indoor_M} />
          <mesh name="CouchUP_LP_Indoor_M_0" geometry={nodes.CouchUP_LP_Indoor_M_0.geometry} material={materials.Indoor_M} />
          <mesh name="Desktop_LP_Indoor_M_0" geometry={nodes.Desktop_LP_Indoor_M_0.geometry} material={materials.Indoor_M} position={[0, 1.506, 2.367]} scale={[1.133, 1, 0.597]} />
          <mesh name="Bolt_LP_wheel_M_0" geometry={nodes.Bolt_LP_wheel_M_0.geometry} material={materials.wheel_M} position={[-2.566, -0.111, -4.454]} rotation={[0, 0, Math.PI]} />
          <mesh name="CWheel_LP_wheel_M_0" geometry={nodes.CWheel_LP_wheel_M_0.geometry} material={materials.wheel_M} position={[2.566, -0.111, -4.454]} />
          <mesh name="Wheel_LP_wheel_M_0" geometry={nodes.Wheel_LP_wheel_M_0.geometry} material={materials.wheel_M} />
        </group>
      </group>
      <group name="Desk" position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={materials['BlackWood.001']} />
        <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={materials['GrayPlastic.001']} />
        <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={materials['BlackPlastic.001']} />
      </group>
      <group name="SM_ShelfSM_Shelf1" position={[-0.868, 1.694, -1.99]}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['795548.001']} />
      </group>
      <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
        <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.002']} />
      </group>
      <mesh name="WawaRug" geometry={nodes.WawaRug.geometry} material={materials.Rug} position={[-0.281, 0.009, 0.765]} />
      <group name="keyboard" position={[-0.044, 0.981, -1.346]} rotation={[0, -0.165, 0]}>
        <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
        <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
        <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
        <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
      </group>
      <group name="iMac" position={[0.454, 0.939, -1.723]} rotation={[Math.PI, -1.099, Math.PI]}>
        <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={materials.Screen} />
        <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={materials.ScreenBlack} />
        <mesh name="iMac_1_2" geometry={nodes.iMac_1_2.geometry} material={materials.iMacBody} />
      </group>
      <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.003']} />
      <group name="Houseplant_7" position={[-2.019, -0.042, -1.526]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={materials['Black.001']} />
        <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={materials['Brown.001']} />
        <mesh name="Houseplant_7_3" geometry={nodes.Houseplant_7_3.geometry} material={materials['Plant_Green.001']} />
      </group>
      <group name="palm_tree_01" position={[2.13, -0.081, -1.055]} rotation={[-Math.PI, 0.672, -Math.PI]}>
        <mesh name="palm_tree_01-Mesh" geometry={nodes['palm_tree_01-Mesh'].geometry} material={materials['795548.001']} />
        <mesh name="palm_tree_01-Mesh_1" geometry={nodes['palm_tree_01-Mesh_1'].geometry} material={materials['8BC34A.001']} />
        <mesh name="palm_tree_01-Mesh_2" geometry={nodes['palm_tree_01-Mesh_2'].geometry} material={materials['DD9944.001']} />
      </group>
      <group name="Chair" position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      </group>
      <mesh name="a378cdfe-b0db-441e-9ab1-aaedf4d06f37" geometry={nodes['a378cdfe-b0db-441e-9ab1-aaedf4d06f37'].geometry} material={materials['a378cdfe-b0db-441e-9ab1-aaedf4d06f37']} position={[-0.552, 1.039, -1.235]} rotation={[Math.PI / 2, 0, -0.733]} scale={[0.174, 0.172, 0.172]} />
      <group name="Node" position={[-0.646, 1.033, -1.341]} rotation={[Math.PI, -0.743, Math.PI]} scale={[0.534, 0.349, 0.792]}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials.mat21} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials.mat22} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials.mat15} />
        <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials['mat24.001']} />
      </group>
      <group name="group18749491" position={[-0.824, 1.315, -1.675]} scale={0.581}>
        <mesh name="mesh18749491" geometry={nodes.mesh18749491.geometry} material={materials.mat20} />
        <mesh name="mesh18749491_1" geometry={nodes.mesh18749491_1.geometry} material={materials.mat24} />
      </group>
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Floor} />
      <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.White} />
      <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.Wall} />
      <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/sala.gltf')
